export component Button {
    in-out property<string> btn_text: "";
    out property <bool> has_hover: touch-area.has-hover;
    height: 40px;
    width: 300px;
    callback on_click;


    touch-area := TouchArea {
        x: 0;
        width: 100%;
        height: 100%;
        clicked => {
            parent.on_click();
        }
    }
    rect := Rectangle {
        x: 0;
        background: #e67e22;
        opacity: touch-area.has-hover || touch-area.pressed ? 0.7 : 1;
        height: 100%;
        width:  100%;
        border-width: 0.5px;
        border-color: #000000;
        animate opacity {
            duration: 0.3s;
            easing: ease-in; 
        }

        Text {
            horizontal-alignment: center;
            vertical-alignment: center;
            text: btn_text;
            font-weight: 700;
            font-size: 16px;
        }
        
    }
}